---
- name: Webserver
  hosts: all
  become: yes
  tasks:
    - name: httpd block
      block:
        - name: Httpd is installed or not
          yum:
            list: httpd
          register: output
          failed_when: output.rc == 1
      rescue:
        - debug:
            msg: "Httpd is already installed"
    - name: Creating log
      file:
        path: /var/www/html/logs
        mode: 0755
        state: directory
    - name: Creating html
      copy:
        content: "{{ ansible_fqdn }} ({{ ansible_default_ipv4.address }}) has been customized"
        dest: /var/www/html/index.html
